//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvzon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>svt1.svt.se</string>\r\n  <string>svt1hd.svt.se</string>\r\n  <string>svt2.svt" +
            ".se</string>\r\n  <string>svt2hd.svt.se</string>\r\n  <string>tv3.se</string>\r\n  <st" +
            "ring>hd.tv3.se</string>\r\n  <string>tv4.se</string>\r\n  <string>hd.tv4.se</string>" +
            "\r\n  <string>fakta.tv4.se</string>\r\n  <string>film.tv4.se</string>\r\n  <string>spo" +
            "rt.tv4.se</string>\r\n  <string>news.tv4.se</string>\r\n  <string>kanal5.se</string>" +
            "\r\n  <string>hd.kanal5.se</string>\r\n  <string>tv6.se</string>\r\n  <string>tnt-tv.s" +
            "e</string>\r\n  <string>sjuan.se</string>\r\n  <string>tv11.tv4.se</string>\r\n  <stri" +
            "ng>tv8.se</string>\r\n  <string>kanal9.se</string>\r\n  <string>tv10.se</string>\r\n  " +
            "<string>axess.se</string>\r\n  <string>showtime.nonstop.tv</string>\r\n  <string>sil" +
            "ver.nonstop.tv</string>\r\n  <string>tcmeurope.com</string>\r\n  <string>eurosport.s" +
            "e</string>\r\n  <string>eurosport2.se</string>\r\n  <string>kanalglobal.se</string>\r" +
            "\n  <string>animalplanet.se</string>\r\n  <string>discoverychannel.se</string>\r\n  <" +
            "string>science.discoverychannel.com</string>\r\n  <string>tlcsverige.se</string>\r\n" +
            "  <string>hd.natgeo.se</string>\r\n  <string>cartoonnetwork.se</string>\r\n  <string" +
            ">disneychannel.se</string>\r\n  <string>xd.disneychannel.se</string>\r\n  <string>bb" +
            "cworldnews.com</string>\r\n  <string>nickelodeon.se</string>\r\n  <string>comedycent" +
            "ral.tv</string>\r\n  <string>mtv.se</string>\r\n  <string>hd.mtv.se</string>\r\n  <str" +
            "ing>star.nonstop.tv</string>\r\n  <string>vh1.se</string>\r\n  <string>cnn.com</stri" +
            "ng>\r\n  <string>kunskapskanalen.svt.se</string>\r\n  <string>svtb-svt24.svt.se</str" +
            "ing>\r\n  <string>travelchanneltv.se</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Channels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Channels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\DVBLogic\\DVBLink\\xmltv\\tvzon.xml")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Days {
            get {
                return ((int)(this["Days"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SerializableStringDictionary ImageCache {
            get {
                return ((global::SerializableStringDictionary)(this["ImageCache"]));
            }
            set {
                this["ImageCache"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DaysInHistory {
            get {
                return ((int)(this["DaysInHistory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteToLog {
            get {
                return ((bool)(this["WriteToLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PreviousShownDuration {
            get {
                return ((int)(this["PreviousShownDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InsertEpisodeInDesc {
            get {
                return ((bool)(this["InsertEpisodeInDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/channels-Sweden.xml.gz")]
        public string ChannelsUrl {
            get {
                return ((string)(this["ChannelsUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/datalist.xml.gz")]
        public string ChannelsLastModifiedUrl {
            get {
                return ((string)(this["ChannelsLastModifiedUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/{0}_{1:yyyy-MM-dd}.xml.gz")]
        public string ChannelUrl {
            get {
                return ((string)(this["ChannelUrl"]));
            }
            set {
                this["ChannelUrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <SerializableStringDictionary>\r\n      <ArrayOfAnyType xmlns:xsi=\"http://ww" +
            "w.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r" +
            "\n       <anyType xsi:type=\"Node\">\r\n        <key>tnt-tv.se</key>\r\n        <val>tv" +
            "7</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>kanal" +
            "5.se</key>\r\n        <val>kanal5</val>\r\n       </anyType>\r\n       <anyType xsi:ty" +
            "pe=\"Node\">\r\n        <key>star.nonstop.tv</key>\r\n        <val>star!</val>\r\n      " +
            " </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>kunskapskanalen.svt." +
            "se</key>\r\n        <val>kunskapskanalen</val>\r\n       </anyType>\r\n       <anyType" +
            " xsi:type=\"Node\">\r\n        <key>kanalglobal.se</key>\r\n        <val>kanalglobal</" +
            "val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>silver.n" +
            "onstop.tv</key>\r\n        <val>silver</val>\r\n       </anyType>\r\n       <anyType x" +
            "si:type=\"Node\">\r\n        <key>svtb-svt24.svt.se</key>\r\n        <val>barnkanalen<" +
            "/val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>nickelo" +
            "deon.se</key>\r\n        <val>nickelodeon</val>\r\n       </anyType>\r\n       <anyTyp" +
            "e xsi:type=\"Node\">\r\n        <key>svt1.svt.se</key>\r\n        <val>svt1</val>\r\n   " +
            "    </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>disneychannel.se<" +
            "/key>\r\n        <val>disneychannel</val>\r\n       </anyType>\r\n       <anyType xsi:" +
            "type=\"Node\">\r\n        <key>kanal9.se</key>\r\n        <val>kanal9</val>\r\n       </" +
            "anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>tv10.se</key>\r\n        " +
            "<val>tv10</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <k" +
            "ey>showtime.nonstop.tv</key>\r\n        <val>showtime</val>\r\n       </anyType>\r\n  " +
            "     <anyType xsi:type=\"Node\">\r\n        <key>tv6.se</key>\r\n        <val>tv6</val" +
            ">\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>tv8.se</key" +
            ">\r\n        <val>tv8</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n" +
            "        <key>film.tv4.se</key>\r\n        <val>tv4film</val>\r\n       </anyType>\r\n " +
            "      <anyType xsi:type=\"Node\">\r\n        <key>cartoonnetwork.se</key>\r\n        <" +
            "val>cartoonnetwork</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n " +
            "       <key>hd.mtv.se</key>\r\n        <val>mtvn-hd</val>\r\n       </anyType>\r\n    " +
            "   <anyType xsi:type=\"Node\">\r\n        <key>sjuan.se</key>\r\n        <val>sjuan</v" +
            "al>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>hd.tv4.se" +
            "</key>\r\n        <val>tv4hd</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"N" +
            "ode\">\r\n        <key>tv11.tv4.se</key>\r\n        <val>tv11</val>\r\n       </anyType" +
            ">\r\n       <anyType xsi:type=\"Node\">\r\n        <key>svt1hd.svt.se</key>\r\n        <" +
            "val>svt1hd</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <" +
            "key>science.discoverychannel.com</key>\r\n        <val>discoveryscience</val>\r\n   " +
            "    </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>xd.disneychannel." +
            "se</key>\r\n        <val>disneyxd</val>\r\n       </anyType>\r\n       <anyType xsi:ty" +
            "pe=\"Node\">\r\n        <key>animalplanet.se</key>\r\n        <val>animalplanet</val>\r" +
            "\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>discoverychan" +
            "nel.se</key>\r\n        <val>discovery</val>\r\n       </anyType>\r\n       <anyType x" +
            "si:type=\"Node\">\r\n        <key>travelchanneltv.se</key>\r\n        <val>travel</val" +
            ">\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>tcmeurope.c" +
            "om</key>\r\n        <val>tcm</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"N" +
            "ode\">\r\n        <key>bbcworldnews.com</key>\r\n        <val>bbcworld</val>\r\n       " +
            "</anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>mtv.se</key>\r\n       " +
            " <val>mtv</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <k" +
            "ey>sport.tv4.se</key>\r\n        <val>tv4sport</val>\r\n       </anyType>\r\n       <a" +
            "nyType xsi:type=\"Node\">\r\n        <key>axess.se</key>\r\n        <val>axesstv</val>" +
            "\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>eurosport2.s" +
            "e</key>\r\n        <val>eurosport2</val>\r\n       </anyType>\r\n       <anyType xsi:t" +
            "ype=\"Node\">\r\n        <key>cnn.com</key>\r\n        <val>cnn</val>\r\n       </anyTyp" +
            "e>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>hd.tv3.se</key>\r\n        <val" +
            ">tv3hd</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>" +
            "eurosport.se</key>\r\n        <val>eurosport</val>\r\n       </anyType>\r\n       <any" +
            "Type xsi:type=\"Node\">\r\n        <key>hd.kanal5.se</key>\r\n        <val>kanal5hd</v" +
            "al>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>svt2.svt." +
            "se</key>\r\n        <val>svt2</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"" +
            "Node\">\r\n        <key>svt2hd.svt.se</key>\r\n        <val>svt2hd</val>\r\n       </an" +
            "yType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>tlcsverige.se</key>\r\n    " +
            "    <val>tlc</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"Node\">\r\n       " +
            " <key>tv3.se</key>\r\n        <val>tv3</val>\r\n       </anyType>\r\n       <anyType x" +
            "si:type=\"Node\">\r\n        <key>tv4.se</key>\r\n        <val>tv4</val>\r\n       </any" +
            "Type>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>hd.natgeo.se</key>\r\n      " +
            "  <val>nationalgeographichd</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"" +
            "Node\">\r\n        <key>fakta.tv4.se</key>\r\n        <val>tv4fakta</val>\r\n       </a" +
            "nyType>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>comedycentral.tv</key>\r\n" +
            "        <val>comedycentral</val>\r\n       </anyType>\r\n       <anyType xsi:type=\"N" +
            "ode\">\r\n        <key>news.tv4.se</key>\r\n        <val>tv4news</val>\r\n       </anyT" +
            "ype>\r\n       <anyType xsi:type=\"Node\">\r\n        <key>vh1.se</key>\r\n        <val>" +
            "vh1</val>\r\n       </anyType>\r\n      </ArrayOfAnyType>\r\n     </SerializableString" +
            "Dictionary>\r\n    ")]
        public global::SerializableStringDictionary TvNuMappings {
            get {
                return ((global::SerializableStringDictionary)(this["TvNuMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChannelSettings {
            get {
                return ((string)(this["ChannelSettings"]));
            }
        }
    }
}
