//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvzon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\DVBLogic\\DVBLink\\xmltv\\tvzon.xml")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SerializableStringDictionary ImageCache {
            get {
                return ((global::SerializableStringDictionary)(this["ImageCache"]));
            }
            set {
                this["ImageCache"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DaysInHistory {
            get {
                return ((int)(this["DaysInHistory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteToLog {
            get {
                return ((bool)(this["WriteToLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PreviousShownDuration {
            get {
                return ((int)(this["PreviousShownDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InsertEpisodeInDesc {
            get {
                return ((bool)(this["InsertEpisodeInDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/channels-Sweden.xml.gz")]
        public string ChannelsUrl {
            get {
                return ((string)(this["ChannelsUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/datalist.xml.gz")]
        public string ChannelsLastModifiedUrl {
            get {
                return ((string)(this["ChannelsLastModifiedUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmltv.xmltv.se/{0}_{1:yyyy-MM-dd}.xml.gz")]
        public string ChannelUrl {
            get {
                return ((string)(this["ChannelUrl"]));
            }
            set {
                this["ChannelUrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>svt1hd.svt.se</string>
  <string>svt2hd.svt.se</string>
  <string>hd.tv3.se</string>
  <string>hd.tv4.se</string>
  <string>film.tv4.se</string>
  <string>news.tv4.se</string>
  <string>hd.kanal5.se</string>
  <string>tv6.se</string>
  <string>sjuan.se</string>
  <string>tv8.se</string>
  <string>kanal9.se</string>
  <string>discoverychannel.se</string>
  <string>disneychannel.se</string>
  <string>kunskapskanalen.svt.se</string>
  <string>svtb-svt24.svt.se</string>
  <string>emotion.cmore.se</string>
  <string>sf-kanalen.cmore.se</string>
  <string>first.cmore.se</string>
  <string>series.cmore.se</string>
  <string>hitshd.cmore.se</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Channels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Channels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Days {
            get {
                return ((int)(this["Days"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t\t\t<SerializableStringDictionary>\r\n\t\t\t\t\t\t<ArrayOfAnyType xmlns:xsi=\"http://ww" +
            "w.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r" +
            "\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>first.cmore.se</key>\r\n\t\t\t\t\t\t\t\t<v" +
            "al>c-more-first</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t" +
            "\t\t\t\t<key>sf-kanalen.cmore.se</key>\r\n\t\t\t\t\t\t\t\t<val>sf-kanalen</val>\r\n\t\t\t\t\t\t\t</anyT" +
            "ype>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>series.cmore.se</key>\r\n\t\t\t\t" +
            "\t\t\t\t<val>c-more-series</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\"" +
            ">\r\n\t\t\t\t\t\t\t\t<key>emotion.cmore.se</key>\r\n\t\t\t\t\t\t\t\t<val>c-more-emotion</val>\r\n\t\t\t\t\t" +
            "\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>hitshd.cmore.se</ke" +
            "y>\r\n\t\t\t\t\t\t\t\t<val>c-more-hits-hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:ty" +
            "pe=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>svt1.svt.se</key>\r\n\t\t\t\t\t\t\t\t<val>svt1</val>\r\n\t\t\t\t\t\t\t</an" +
            "yType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>svt2.svt.se</key>\r\n\t\t\t\t\t\t" +
            "\t\t<val>svt2</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t" +
            "<key>svt1hd.svt.se</key>\r\n\t\t\t\t\t\t\t\t<val>svt1hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<" +
            "anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>svt2hd.svt.se</key>\r\n\t\t\t\t\t\t\t\t<val>svt2hd<" +
            "/val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tv3.se<" +
            "/key>\r\n\t\t\t\t\t\t\t\t<val>tv3</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node" +
            "\">\r\n\t\t\t\t\t\t\t\t<key>hd.tv3.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv3hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t" +
            "\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tv4.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv4</va" +
            "l>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>hd.tv4.se<" +
            "/key>\r\n\t\t\t\t\t\t\t\t<val>tv4hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"No" +
            "de\">\r\n\t\t\t\t\t\t\t\t<key>kanal5.se</key>\r\n\t\t\t\t\t\t\t\t<val>kanal5</val>\r\n\t\t\t\t\t\t\t</anyType>" +
            "\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>hd.kanal5.se</key>\r\n\t\t\t\t\t\t\t\t<va" +
            "l>kanal5hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<" +
            "key>fakta.tv4.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv4fakta</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<" +
            "anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>film.tv4.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv4film</" +
            "val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>sport.tv" +
            "4.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv4sport</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:" +
            "type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>news.tv4.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv4news</val>\r\n\t\t\t\t\t\t" +
            "\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tv6.se</key>\r\n\t\t\t\t\t\t" +
            "\t\t<val>tv6</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<" +
            "key>tnt-tv.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv7</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType " +
            "xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>sjuan.se</key>\r\n\t\t\t\t\t\t\t\t<val>sjuan</val>\r\n\t\t\t\t\t\t\t" +
            "</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tv11.tv4.se</key>\r\n\t\t" +
            "\t\t\t\t\t\t<val>tv11</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t" +
            "\t\t\t\t<key>tv8.se</key>\r\n\t\t\t\t\t\t\t\t<val>tv8</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyTyp" +
            "e xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>kanal9.se</key>\r\n\t\t\t\t\t\t\t\t<val>kanal9</val>\r\n\t\t\t" +
            "\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tv10.se</key>\r\n\t\t" +
            "\t\t\t\t\t\t<val>tv10</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t" +
            "\t\t\t\t<key>axess.se</key>\r\n\t\t\t\t\t\t\t\t<val>axesstv</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<" +
            "anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>showtime.nonstop.tv</key>\r\n\t\t\t\t\t\t\t\t<val>s" +
            "howtime</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key" +
            ">silver.nonstop.tv</key>\r\n\t\t\t\t\t\t\t\t<val>silver</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<" +
            "anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>tcmeurope.com</key>\r\n\t\t\t\t\t\t\t\t<val>tcm</va" +
            "l>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>eurosport." +
            "se</key>\r\n\t\t\t\t\t\t\t\t<val>eurosport</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:t" +
            "ype=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>eurosport2.se</key>\r\n\t\t\t\t\t\t\t\t<val>eurosport2</val>\r\n\t\t" +
            "\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>kanalglobal.se</" +
            "key>\r\n\t\t\t\t\t\t\t\t<val>kanalglobal</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:typ" +
            "e=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>animalplanet.se</key>\r\n\t\t\t\t\t\t\t\t<val>animalplanet</val>\r\n" +
            "\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>discoverychann" +
            "el.se</key>\r\n\t\t\t\t\t\t\t\t<val>discovery</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xs" +
            "i:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>science.discoverychannel.com</key>\r\n\t\t\t\t\t\t\t\t<val>di" +
            "scoveryscience</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t" +
            "\t\t\t<key>tlcsverige.se</key>\r\n\t\t\t\t\t\t\t\t<val>tlc</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<" +
            "anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>hd.natgeo.se</key>\r\n\t\t\t\t\t\t\t\t<val>national" +
            "geographichd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t" +
            "\t<key>cartoonnetwork.se</key>\r\n\t\t\t\t\t\t\t\t<val>cartoonnetwork</val>\r\n\t\t\t\t\t\t\t</anyTy" +
            "pe>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>disneychannel.se</key>\r\n\t\t\t\t" +
            "\t\t\t\t<val>disneychannel</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\"" +
            ">\r\n\t\t\t\t\t\t\t\t<key>xd.disneychannel.se</key>\r\n\t\t\t\t\t\t\t\t<val>disneyxd</val>\r\n\t\t\t\t\t\t\t<" +
            "/anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>bbcworldnews.com</key>" +
            "\r\n\t\t\t\t\t\t\t\t<val>bbcworld</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node" +
            "\">\r\n\t\t\t\t\t\t\t\t<key>nickelodeon.se</key>\r\n\t\t\t\t\t\t\t\t<val>nickelodeon</val>\r\n\t\t\t\t\t\t\t</" +
            "anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>comedycentral.tv</key>\r" +
            "\n\t\t\t\t\t\t\t\t<val>comedycentral</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"" +
            "Node\">\r\n\t\t\t\t\t\t\t\t<key>mtv.se</key>\r\n\t\t\t\t\t\t\t\t<val>mtv</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t" +
            "\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>hd.mtv.se</key>\r\n\t\t\t\t\t\t\t\t<val>mtvn-" +
            "hd</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>star" +
            ".nonstop.tv</key>\r\n\t\t\t\t\t\t\t\t<val>star!</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType " +
            "xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>vh1.se</key>\r\n\t\t\t\t\t\t\t\t<val>vh1</val>\r\n\t\t\t\t\t\t\t</an" +
            "yType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>cnn.com</key>\r\n\t\t\t\t\t\t\t\t<v" +
            "al>cnn</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>" +
            "kunskapskanalen.svt.se</key>\r\n\t\t\t\t\t\t\t\t<val>kunskapskanalen</val>\r\n\t\t\t\t\t\t\t</anyTy" +
            "pe>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">\r\n\t\t\t\t\t\t\t\t<key>svtb-svt24.svt.se</key>\r\n\t\t\t" +
            "\t\t\t\t\t<val>barnkanalen</val>\r\n\t\t\t\t\t\t\t</anyType>\r\n\t\t\t\t\t\t\t<anyType xsi:type=\"Node\">" +
            "\r\n\t\t\t\t\t\t\t\t<key>travelchanneltv.se</key>\r\n\t\t\t\t\t\t\t\t<val>travel</val>\r\n\t\t\t\t\t\t\t</any" +
            "Type>\r\n\t\t\t\t\t\t</ArrayOfAnyType>\r\n\t\t\t\t\t</SerializableStringDictionary>\r\n\t\t\t\t")]
        public global::SerializableStringDictionary TvNuMappings {
            get {
                return ((global::SerializableStringDictionary)(this["TvNuMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
					{
					channels: [
						{
							channelId: ""hitshd.cmore.se"",
							monday: { start: ""07:00"", end:""16:30""},
							tuesday: { start: ""00:30"", end:""16:30""},
							wednesday: { start: ""00:30"", end:""16:30""},
							thursday: { start: ""00:30"", end:""16:30""},
							friday: { start: ""00:30"", end:""23:59""},
							saturday: { start: ""00:00"", end:""07:00""},
							sunday: { start: ""00:00"", end:""00:00""}
						},
						{
							channelId: ""emotion.cmore.se"",
							monday: { start: ""01:00"", end:""18:30""},
							tuesday: { start: ""01:00"", end:""18:30""},
							wednesday: { start: ""01:00"", end:""18:30""},
							thursday: { start: ""01:00"", end:""18:30""},
							friday: { start: ""01:00"", end:""18:30""},
							saturday: { start: ""00:00"", end:""00:00""},
							sunday: { start: ""00:00"", end:""00:00""}
						},
						{
							channelId: ""sf-kanalen.cmore.se"",
							monday: { start: ""01:00"", end:""18:00""},
							tuesday: { start: ""01:00"", end:""18:00""},
							wednesday: { start: ""01:00"", end:""18:00""},
							thursday: { start: ""01:00"", end:""18:00""},
							friday: { start: ""01:00"", end:""18:00""},
							saturday: { start: ""01:00"", end:""12:00""},
							sunday: { start: ""01:00"", end:""12:00""}
						}
					]
					}
				")]
        public string ChannelSettings {
            get {
                return ((string)(this["ChannelSettings"]));
            }
        }
    }
}
